name: Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Pipeline
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_PROJECT_ID: ${{ secrets.JENKINS_PROJECT_ID }}
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_PROJECT_ID/build?token=$JENKINS_TOKEN" \
          --user "$JENKINS_USER:$JENKINS_TOKEN"
